# Generated by Django 2.0.6 on 2019-05-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='用户密码')),
                ('telephone', models.CharField(max_length=15, unique=True, verbose_name='手机号码')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
